---
abstract: 'a small lightweight SmokeBox'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  HTTP::Date: 0
  HTTP::Response: 0
  POE::Filter::HTTP::Parser: 0.08
  Test::More: 0.47
  Test::POE::Server::TCP: 0.12
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: minismokebox
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Config::Tiny: 2.12
  File::Spec: 0
  POE: 1.0001
  POE::Component::SmokeBox: 0.14
  POE::Component::SmokeBox::Dists: 0.08
  POE::Component::SmokeBox::Recent: 1.12
  Pod::Usage: 1.00
  Time::Duration: 1.06
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/minismokebox.git
version: 0.18
