---
abstract: 'a small lightweight SmokeBox'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Date: 0
  HTTP::Response: 0
  POE::Filter::HTTP::Parser: 0.08
  Test::More: 0.47
  Test::POE::Server::TCP: 0.12
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: minismokebox
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  App::SmokeBox::Mini:
    file: lib/App/SmokeBox/Mini.pm
    version: 0.40
  App::SmokeBox::Mini::Plugin:
    file: lib/App/SmokeBox/Mini/Plugin.pm
    version: 0.40
  POE::Component::SmokeBox::Backend::Test::SmokeBox::Mini:
    file: lib/POE/Component/SmokeBox/Backend/Test/SmokeBox/Mini.pm
    version: 0.40
requires:
  App::SmokeBox::PerlVersion: 0.06
  Config::Tiny: 2.12
  File::Path: 0
  File::Spec: 0
  Module::Load: 0
  Module::Pluggable: 0
  POE: 1.005
  POE::Component::SmokeBox: 0.36
  POE::Component::SmokeBox::Dists: 1.04
  POE::Component::SmokeBox::Recent: 1.28
  Pod::Usage: 1.00
  Time::Duration: 1.06
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/minismokebox/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/minismokebox.git
version: 0.40
